export const FBET_ASSET_ID = 1002;

export const LOTTERY_APP_ID = 1007;
export const LOTTERY_APP_ADDRESS =
  "XH7HGWREAK4KN4JOTHNURKMQHYSOYOPT4WR5Z46ZLECBCYUAF2T2JOFUOQ";

export const ALGO_DECIMALS = 1e6;
export const FBET_DECIMALS = 1e4;
